### ISSUE TITLE
Changes on moving around

### ISSUE THREAD

**Issue by MesaBlack** [violetfrost/violetfrost.github.io#1]
rn you have to right click to look AND MOVE around

Here's what I want:
left click to look around
wasd (move) speed is a bit faster and you don't need to hold down two fingers

Also I get this "press esc to view your cursor"

**Comment by violetfrost** [comment]
I'll work on making this work a little better with trackpads - thanks for the feedback - will update soon!

**Comment by MesaBlack** [comment]
since this is no longer a good idea for movement
