### ISSUE TITLE
Here's one asset for a search bar along with a mockup.

### ISSUE THREAD

**Issue by MesaBlack** [violetfrost/violetfrost.github.io#16]
![search icon v4](https://github.com/violetfrost/violetfrost.github.io/assets/132141735/bc2d47ba-83b9-4832-9f9a-ba869ba0d8af)

Mockup:
![searchbar mockup](https://github.com/violetfrost/violetfrost.github.io/assets/132141735/ad80d331-7cc1-4915-a877-d108d160b63a)

The color for the search bar outline/text (and the provided svg) is `#E29886`

**Comment by MesaBlack** [comment]
![mobile search mock](https://github.com/violetfrost/violetfrost.github.io/assets/132141735/20ec2cab-50d6-4fa4-8f54-7a600e71c494)

This is a mockup of the search bar in mobile

**Comment by violetfrost** [comment]
I actually dig this idea; might be cool when I get around to adding more data to buildings and whatnot - will see about implementing something like this

**Comment by MesaBlack** [comment]
The first thing we'll search with can be a set of coordinates

**Comment by burnsboyamazing** [comment]
No search bar and no "Find a place" and can't search in GTA 6 maps.
[Screen recording 2023-12-26 8.21.08 PM.webm](https://github.com/violetfrost/violetfrost.github.io/assets/154830140/12ee99c1-0997-4eb2-aebd-45bef9f77161)
