### ISSUE TITLE
Heck's this effect?

### ISSUE THREAD

**Issue by MesaBlack** [violetfrost/violetfrost.github.io#18]
![image](https://github.com/violetfrost/violetfrost.github.io/assets/132141735/2501ffbe-c94d-44ae-8c34-b3584469ba29)

**Comment by violetfrost** [comment]
Screen-space Ambient Occlusion

**Comment by MesaBlack** [comment]
what do you use it for?

**Comment by MesaBlack** [comment]
I meant what's that stuff between the buildings
