### ISSUE TITLE
Huh?

### ISSUE THREAD

**Issue by MesaBlack** [violetfrost/violetfrost.github.io#19]
![Screenshot 2023-12-16 6 20 53 PM](https://github.com/violetfrost/violetfrost.github.io/assets/132141735/8bf54383-9091-4475-9cbd-0bb1a0aee0b2)

**Comment by violetfrost** [comment]
UX 101 - put a button in both commonly used places so there isn't as much friction.

**Comment by MesaBlack** [comment]
Ah.
