### ISSUE TITLE
How to move and look around in mobile

### ISSUE THREAD

**Issue by MesaBlack** [violetfrost/violetfrost.github.io#2]
You can have 2 halves of the screen. The left, when tapped shows a look around joystick. The right one, a joystick for moving around

**Comment by violetfrost** [comment]
Definitely want mobile support, just haven't had the time to do it myself - if anyone with JS experience is reading that wants to help hit me up and I can send you the unprocessed source.

**Comment by MesaBlack** [comment]
I think I have a better idea:
Make the mobile version like a real Maps app.
