### ISSUE TITLE
Have the trees disappear when viewed from afar.

### ISSUE THREAD

**Issue by MesaBlack** [violetfrost/violetfrost.github.io#33]
[Screen recording 2023-12-18 1.14.23 PM.webm](https://github.com/violetfrost/violetfrost.github.io/assets/132141735/65b255b7-48c4-4f21-84b3-9078bde13256)

**Comment by violetfrost** [comment]
Going to push an emergency hotfix for this one, didn't even consider how this would perform on lower end devices, thank you!

**Comment by MesaBlack** [comment]
I run on an intel core i3 chromebook

**Comment by violetfrost** [comment]
Added foliage render distance - thanks again!
