### ISSUE TITLE
something with mobile that's bound to give someone seizures

### ISSUE THREAD

**Issue by MesaBlack** [violetfrost/violetfrost.github.io#37]
https://github.com/violetfrost/violetfrost.github.io/assets/132141735/6eebb9e1-488a-4390-aa04-972c7a21ea16

**Comment by violetfrost** [comment]
What android version / what browser / any other pertinent information? This is because it's falling back to the default depth buffer (ie. non lograithmic) so I'm guessing it's an issue of what versions of WebGL your device supports.

**Comment by MesaBlack** [comment]
Google Chrome on a Samsung Galaxy A12

**Comment by violetfrost** [comment]
What OS version, though? Settings -> About Phone -> Android Version

**Comment by MesaBlack** [comment]
**Android 12**. Apple's iPhone (you use one) has its own iOS, and they don't license the OS to third parties. Samsung mostly runs on android. as do most other non-apple companies.

**Comment by violetfrost** [comment]
So far this is looking to be a bug specific to android 12+ on samsung phones and maybe pixel with WebGL - system level and I can't fix it if that is the case.

Just in case, though, one more question: What version of chrome do you use? Chrome settings -> about chrome

**Comment by MesaBlack** [comment]
Chrome 120.0.6099.115

appears to be fixed btw

**Comment by MesaBlack** [comment]
https://github.com/violetfrost/violetfrost.github.io/assets/132141735/24d1e613-ecf9-4a0a-99bc-0970dd616fe3

looks okay on mine now.
