### ISSUE TITLE
Skybox is black on mobile

### ISSUE THREAD

**Issue by MesaBlack** [violetfrost/violetfrost.github.io#38]
Device: Samsung Galaxy A12

Android Version: 12

![IMG_20231218_135459](https://github.com/violetfrost/violetfrost.github.io/assets/132141735/4beea8b4-07d5-4140-9c8e-41426e2fa83a)

Was this after the flickering fix?

(might give us an idea of dark mode)

**Comment by violetfrost** [comment]
I haven't made any codebase changes, interesting to see that you're no longer experiencing issues. Might be something to do with VRAM, will look into it.

**Comment by MesaBlack** [comment]
might as well check out the other ideas strewn about
