### ISSUE TITLE
This venetian island looks a bit off

### ISSUE THREAD

**Issue by MesaBlack** [violetfrost/violetfrost.github.io#43]
![Screenshot 2023-12-18 5 09 42 PM](https://github.com/violetfrost/violetfrost.github.io/assets/132141735/404f8e8c-a210-4ce9-8228-e043faf270a9)

**Comment by violetfrost** [comment]
fixed in v6

**Comment by MesaBlack** [comment]
Are we currently running on 5?

> fixed in v6
