### ISSUE TITLE
The ability to swap with DuPz0r's map (which can update)

### ISSUE THREAD

**Issue by MesaBlack** [violetfrost/violetfrost.github.io#6]
Curious if any way to link with https://vimap.saamexe.com/map

Disclaimer: There might be inconsistencies in the position of certain buildings

Oh and it works more with those navigation features cause of the roads. Even if most are speculative.

**Comment by violetfrost** [comment]
Not viable, the 3D map relies too much on the positionings of fido's map and eventually will cover up the 2D layer entirely

**Comment by MesaBlack** [comment]
oh
